sweep:
  dir: /checkpoint/${env:USER}/space/gan/${env:PREFIX}/${hydra.job.name}
  subdir: ${hydra.job.num}
launcher:
  submitit_folder: ${hydra.sweep.dir}
  timeout_min: 4320
  cpus_per_task: 64
  gpus_per_node: 8
  tasks_per_node: 1
  mem_gb: 400
  nodes: 1
  name: ${env:PREFIX}_${hydra.job.config_name}
  # partition: devlab,learnlab,learnfair,scavenge
  # constraint: volta32gb
  # max_num_timeout: 30
  # exclude: learnfair1381,learnfair5192,learnfair2304